### PR TITLE
feat: Add naming strategy and purge old attributes

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 @shreyasnbhat Please review

**Review by Shailesh351 — APPROVED** [review]
Great!! :tada:

**Comment by Shailesh351** [comment]
@iamareebjamal Should i make same changes in Android App ?

**Review by shreyasnbhat — APPROVED** [review]

**Comment by iamareebjamal** [comment]
@Shailesh351 Please go ahead. But first let @arp95's PR get merged. You can create branch from his PR and start working on it

**Comment by iamareebjamal** [comment]
Also, a recommendation, I have added ignorable attributes so that the app does not crash if API changes, but you'd want to test if the attributes are mapping properly. So, remove the ignorable property annotation while testing but always add it later

**Pull request merged**
