### PR TITLE
chore : Remove unnecessary code from event models

### PR DESCRIPTION
**Pull request by Shailesh351**
Removed unnecessary code from following models : 
- Event
- ApiEvent
- SocialLink
- Copy Right
- CallForSpeakers

### CODE REVIEW

**Comment by Shailesh351** [comment]
@iamareebjamal @arp95 Please review.

**Comment by iamareebjamal** [comment]
@Shailesh351 Does removing this make any difference `@JsonInclude(JsonInclude.Include.NON_NULL)`

**Comment by Shailesh351** [comment]
No it is not making any difference i have checked. And actually we don't want to only include non null attributes because we want all attributes.

And also i think this include will be only used while serialization. 

So removing it also

**Review by iamareebjamal — APPROVED** [review]

**Review by arp95 — APPROVED** [review]
LGTM.

**Pull request merged**
