### PR TITLE
feat: Merge redundant models

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 As you can see that microlocation model for both old and new API became same, so I merged it.

Track is ready to merge too but we can't as it contains dependency on Session which is a little bit different for both APIs. So, the next task is to find such same models, and merge them into one.

I'm working on Sponsor and sessiontype

**Comment by iamareebjamal** [comment]
Well Sponsor has different endpoints too, so that leaves sessiontype. I'll add it in same PR. Please make a list of different end point names in both api, so that we can create a table for server guys to look at

**Comment by arp95** [comment]
working on that then

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 Please review. A lot of changes now

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 
have made a table for changes in old and new api. please see.
The event model has a lot of changes, so didnt include that.

Link: https://docs.google.com/document/d/1caaCeOOTIxQn2HR1Uj9r-cHXQH5hSYzzzCJpt3rkl38/edit?usp=sharing

**Review by arp95 — APPROVED** [review]
LGTM.

**Review by Shailesh351 — APPROVED** [review]
LGTM

**Pull request merged**
