### PR TITLE
feat: Add lombok to data classes

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 @shreyasnbhat Please review

**Review by Shailesh351 — APPROVED** [review]
Great!! How did you find amazing library like this ? :sweat_smile:

**Comment by Shailesh351** [comment]
I will add lombok data in open event android :+1:

**Review by arp95 — APPROVED** [review]
amazing!

**Comment by shreyasnbhat** [comment]
@iamareebjamal This is pretty cool

**Review by shreyasnbhat — APPROVED** [review]

**Comment by arp95** [comment]
yes please @Shailesh351

**Comment by iamareebjamal** [comment]
@Shailesh351 I knew about lombok and AutoValue from long time but Android Studio support was lacking

**Pull request merged**
