### PR TITLE
feat: Add session relationship to track

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 This is how I was talking about, this way we don't even have to change our old models that much. I'm getting a feeling that we would be able to reuse all of our old models

The only hindrance currently is the handling of IDs as they are string here and long in our old models

**Comment by Shailesh351** [comment]
@iamareebjamal Have you talked to server guys regarding `included`  member will be  there or not? because as per jsonapi specification it is not mandatory to have this member.

**Review by Shailesh351 — APPROVED** [review]

**Comment by iamareebjamal** [comment]
@Shailesh351 Yes I talked to @niranjan94 and he confirmed that server is capable of responding with included fields

**Review by arp95 — APPROVED** [review]
LGTM.

**Pull request merged**
