### PR TITLE
removed same annotations from speaker and sponser model

### PR DESCRIPTION
**Pull request by arp95**
removed same annotations from the model.

@iamareebjamal @Shailesh351 
please review.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@arp95 Please try to remove the annotations at top of the speaker class and see if it works as well

**Comment by arp95** [comment]
@iamareebjamal 
you are talking of the @JsonPropertyOrder one right?

**Comment by iamareebjamal** [comment]
Yes

**Comment by arp95** [comment]
please review now.

**Review by iamareebjamal — APPROVED** [review]

**Review by Shailesh351 — APPROVED** [review]

**Pull request merged**
