### PR TITLE
feat : Add relationships for session model

### PR DESCRIPTION
**Pull request by Shailesh351**
Changes:
- Added relationships(session-type, track, microlocation, speakers) for session model
- Moved IO related methods to IOUtils class

### CODE REVIEW

**Comment by Shailesh351** [comment]
@iamareebjamal @arp95 Please review

**Comment by iamareebjamal** [comment]
@Shailesh351 We only need to have relationship which is directly accessible in 1 JSON, because we won't make 3 API calls just to resolve Session type

**Comment by iamareebjamal** [comment]
So assume that while parsing you only have access to session.json

**Comment by arp95** [comment]
@iamareebjamal but for relationships of session with microlocation, track and speaker we need to make different api calls right. how can we determine the realtionship through one json?

**Comment by Shailesh351** [comment]
@iamareebjamal Main problem is that in current server response they only providing relationship links. So for parsing we have to fetch response from server.

If they provide INCLUDED section also then we can parse whole json without making API calls.

Please suggest other way

**Comment by iamareebjamal** [comment]
Currently, you can manually add included section, as it will be definitely returned by the API

**Comment by iamareebjamal** [comment]
@arp95 The basic info about each relationship will be included in the JSON. Like at least the ID of sessions, or tracks or microlocations

**Comment by iamareebjamal** [comment]
When it will be saved in db, it'll load the whole object because they'll be linked by IDs. When we load from network, we won't be waiting for all calls to complete to then send each to different parsers. This will be a complex task as session track and speakers have circular dependency

**Comment by Shailesh351** [comment]
@iamareebjamal Made changes. Please review

**Review by arp95 — APPROVED** [review]
LGTM.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
